### ISSUE TITLE
add !fullscreen

### ISSUE THREAD

**Issue by NoYavy** [gruener-campus-malchow/CampusSlides#2]
!fullscreen should be an option when adding images to slides

**Comment by eintyp** [comment]
Implemented in the live version, using `!contain` and `!cover` for different scaling behaviors.

Transparent images can be stacked on top of each other.

**Comment by NoYavy** [comment]
In the preview ```!cover``` seems to produce a fullscreen image:
![Screenshot from 2023-03-31 12-25-33](https://user-images.githubusercontent.com/66779682/229095664-b829f8ba-6296-4ab8-9ed4-b2ed839aaeff.png)
But in the actual presentation, there are black borders trimming the image:
![Screenshot from 2023-03-31 12-25-55](https://user-images.githubusercontent.com/66779682/229095669-9fcf061a-1a20-4e00-8bdd-25c84a0d8201.png)
Is this intended behaviour?

**Comment by eintyp** [comment]
Yes, this is intentional. The aspect ratio of a slide is always 4:3, regardless of screen size. Therefore, on a widescreen monitor, you'll get black bars on both sides.
